// <auto-generated />
using System;
using ExerciseLog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExerciseLog.Migrations
{
    [DbContext(typeof(ExerciseLogContext))]
    partial class ExerciseLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExerciseLog.Models.Exercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Exercise_Date");

                    b.Property<string>("Plank_Duration");

                    b.Property<int>("Pushup_Count");

                    b.Property<string>("Run_Distance");

                    b.Property<string>("Run_Duration");

                    b.HasKey("ID");

                    b.ToTable("Exercise");
                });
#pragma warning restore 612, 618
        }
    }
}
